# Generated by Django 2.2.2 on 2019-06-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0005_auto_20190608_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.CharField(max_length=50)),
                ('response', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
