# Generated by Django 2.2.2 on 2019-06-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0006_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='response',
            new_name='feedback',
        ),
    ]
