# Generated by Django 2.2.2 on 2019-06-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0007_auto_20190608_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
