# Generated by Django 2.2.2 on 2019-06-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0012_auto_20190608_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
